### ISSUE TITLE
Number of Initial, Full Submissions and Research Publications by Month report

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline#1]
Count of manuscripts by month of initial qc date (found in XML).

For research content (type: Research Article, Short Report, Advance, Registered Report, Replication Study, Tools and Resources, Scientific Correspondence), by month, over the last ~20 months, report on:

* Number of (first) initial submissions
* Number of (first) full subissions
* Number of (first) publications (poa or typeset)

CSV for report see #24 

- [ ] Create dummy data XML
- [ ] Create data model
- [ ] ETL to Postgres database
- [ ] Make it available to Data Studio
- [ ] Create chart in Data Studio
- [ ] Chart to also show previous period (year)

**Comment by seanwiseman** [comment]
>CSV for report to include the following columns:
...
initial_qc_dt: Timestamp of first Initial QC Complete stage of initial submission
full_qc_dt: Timestamp of first Initial QC Complete stage of full submission
poa_dt: Timestamp of POA (Publication On Acceptance)
vor_dt: Timestamp of VOR (Version Of Record - publication of typeset version)

@de-code should I be populating these in the `csv` along side the existing data?

**Comment by de-code** [comment]
@seanwiseman that CSV (or perhaps database view instead) would be a view of the existing data (going to revise it as we are creating the actual reports). But we need the data in the database. It's largely coming from the _stages_. But it would be good to also have the _poa_dt_ and _vor_dt_ in the database from _Observer_. It's really just saving the response from _Observer_ to CSV and adding CSV headers. I'd be tempted to just import it as a separate table / entity and join it using the view.

**Comment by de-code** [comment]
closing (using milestone instead)
